{% set name = "stringbrewer" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stringbrewer-{{ version }}.tar.gz
  sha256: c2d113822f9393500b273cc833a21ce739036c02c62f47042e0f17ef9b9ea649

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - rstr
    - sre_yield

test:
  imports:
    - stringbrewer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simoncozens/stringbrewer
  summary: Generate random strings matching a pattern
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
